# .github/workflows/spam_detection.yml
name: Spam Detection

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  moderate_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write


    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Spam Detection
      uses: ./  # Runs the Action from the root of the current repo
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        comment_body: ${{ github.event.comment.body }}
# spam_detection.yml (Corrected)
    - name: Hide Comment if Spam
      if: fromJSON(steps.spam_detection.outputs.is_spam).is_spam # Access the 'is_spam' property correctly
      run: |
        gh api -X PATCH /repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }} -f body='[Hidden by automated moderation: spam detected]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
